### PR TITLE
Created a new release version 3.1.0

### PR DESCRIPTION
**Pull request by gmorph**
Upped the minor version number as the message definitions hand't changed in 2 years so this is a big difference.
And ignore my branch version number - I got ahead of myself.  The commit itself is correct i.e. 3.1.0.

### CODE REVIEW

**Review by billbonney — COMMENTED** [review]
When we do a beta release this verb changes to beta. When we do a release I will update this file at that time

**Comment by gmorph** [comment]
Ok.  Can I ask is there many people who pickup the beta for testing?  Am I right in thinking if we create a new Beta for Tower we can only do it off a Stable release of dronekit-android.  So we have to wait for dronekit-android to pass beta testing and then start a Tower beta testing cycle?

**Comment by billbonney** [comment]
Nope. DroneKit-android is bundled with Tower these days. So we don’t need to release DroneKit-Android separately.

**Comment by gmorph** [comment]
I still don't understand the release process.  I'll ask the question in Gitter so all developers can benefit.

**Comment by billbonney** [comment]
I’ll push a beta release at the weekend so we have the most up to day changes.

**Pull request closed without merging**
