### PR TITLE
Update message definitions to latest

### PR DESCRIPTION
**Pull request by gmorph**
I have updated common.xml and ardupilotmega.xml to the latest from ardupilot/modules/mavlink and re-generated the classes accordingly.

### CODE REVIEW

**Comment by billbonney** [comment]
This PR should also fix the starter app as per the older PR to update Mavlink https://github.com/dronekit/dronekit-android/pull/465. Cherry pick the change to allow the starter app to build would be my advice.

**Comment by gmorph** [comment]
@billbonney - your saying merge this change and cheery pick your fix for the starter app?  I think that's a great idea.

**Comment by billbonney** [comment]
@gmorph I was suggesting you pull that change so the StarterApp build with this project, as currently with this change it fails. You don't need to CP it, you can just copy the few lines that fixes the test app.

This PR needs to be made against the default branch, which is develop, not master (master is for stable releases)

The other thing is that I will make the change so that Travis CI builds. Its simple change. The simple rule being all PRs need to verify with Travis before merging.

Thanks 👍

**Comment by gmorph** [comment]
I've created a new PR against the develop branch.  https://github.com/dronekit/dronekit-android/pull/481
I've included your StartApp change.
Lets hope this passes Travis.  Thanks.

**Pull request closed without merging**
