### PR TITLE
 LocationRelay: Overload Constructor with option for LOCATION_ACCURACY_THRESHOLD Option

### PR DESCRIPTION
**Pull request by lordneeko**
The idea here is to keep current compatibility, but create ability for the LocationRelay class to be used with a "Desired Accuracy" value.  It may be more or less accurate than the default (10.0f) but it gives the user the option based on their needs.

### CODE REVIEW

**Comment by lordneeko** [comment]
Would love to see movement in this repo...

**Comment by billbonney** [comment]
You've made your change against a very old commit in the repo. It would be better if you applied for changes to HEAD of develop. (I know they are small, but it means you will get proper credit in the git history by doing that)

NOTE: its's good to submit one commit for this change you can use 'squash' to help you.

If you need help send me a message and I can help.

Thx 👍

**Comment by lordneeko** [comment]
I committed against the LocationRelay file in the develop branch, which shows it is the branch with the latest changes... i don't understand how that's a very old commit.

**Comment by billbonney** [comment]
Sorry, my mistake. I have crated a new Pull Request with a only one commit for the change to make it easier to review the complete change see #485

**Pull request closed without merging**
