### PR TITLE
Bugfix incorrect wifi indicator

### PR DESCRIPTION
**Pull request by djmedina**
Adding support for MAVLINK_MSG_ID_RADIO_STATUS #109

### CODE REVIEW

**Comment by ne0fhyk** [comment]
@djmedina is it possible to undo the formatting made to the file. I'm having a hard time spotting the difference since everything shows as being different.

**Comment by djmedina** [comment]
@ne0fhyk I noticed the same thing. No idea why it did that. I can try rolling back the commit and adding the fix again if you want me to. I think that might cause it to re-do the differences.

**Comment by djmedina** [comment]
@ne0fhyk changes should be a lot more legible now!

**Comment by ne0fhyk** [comment]
@djmedina cool, thx for the update. Looks all good!

**Pull request merged**
